dist: focal
sudo: true
language: python

matrix:
  include:
  - python: 3.9
    name: "Python39"

install:
  - pip install -r requirements.txt
  - export PYTHONPATH=src

script:
  - python setup.py unittests 
