environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_compiler.cmd"

  matrix:

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%\\python -m pip install --upgrade pip"
  - "%PYTHON%\\Scripts\\pip install pymyinstall"
  - "%PYTHON%\\Scripts\\pymy_install3 --set=pyquickhelper"
  - "%PYTHON%\\Scripts\\pip install pyquickhelper"
  - "%PYTHON%\\Scripts\\pip install pycryptodome"
  - "%PYTHON%\\Scripts\\pymy_install3 biopython reportlab basemap"
  - "%PYTHON%\\Scripts\\pip install bokeh"
  - "%PYTHON%\\Scripts\\pip install bqplot"
  - "%PYTHON%\\Scripts\\pip install ete3"
  - "%PYTHON%\\Scripts\\pip install ggplot"
  - "%PYTHON%\\Scripts\\pip install lifelines"
  - "%PYTHON%\\Scripts\\pip install networkx"
  - "%PYTHON%\\Scripts\\pip install seaborn"
  - "%PYTHON%\\Scripts\\pip install plotly"
  - "%PYTHON%\\Scripts\\pip install python-lightning"


build: off

test_script:
  - "%PYTHON%\\python -u setup.py build_script"
  - "%PYTHON%\\python -u setup.py unittests"
