environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_compiler.cmd"

  matrix:

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%\\python -m pip install --upgrade pip"
  - "%PYTHON%\\Scripts\\pip install pymyinstall"
  - "%PYTHON%\\Scripts\\pymy_install3 --set=pyensae"
  - "%PYTHON%\\Scripts\\pip install cryptography"
  - "%PYTHON%\\Scripts\\pip install azure"
  - "%PYTHON%\\Scripts\\pymy_install3 cython cairocffi cairosvg"
  - "%PYTHON%\\Scripts\\pymy_install3 numba pycurl Pillow shapely pyproj"
  - "%PYTHON%\\Scripts\\pymy_install3 sympy mpmath reportlab statsmodels cffi scipy pylzma"
  - "%PYTHON%\\Scripts\\pymy_install3 --task=tool --source=zip graphviz"
  - "%PYTHON%\\Scripts\\pymy_install3 datashader pydy biopython scikit-image pyproj TA_Lib"
  - "%PYTHON%\\Scripts\\pymy_install3 fast_histogram"
  - "%PYTHON%\\Scripts\\pip install -r requirements_conda.txt"
  - "%PYTHON%\\Scripts\\pip install ete3"
  - "%PYTHON%\\Scripts\\pip install git+https://github.com/matplotlib/mpl_finance"
  - "%PYTHON%\\Scripts\\pip install -r requirements.txt"
  - "%PYTHON%\\Scripts\\pip install widgetsnbextension"
  - "set PATH=%PATH%;%PYTHON%\\Scripts"
  - "jupyter nbextension enable --py --sys-prefix widgetsnbextension"
  - "set PATH=%PATH%;C:\\projects\\jupytalk\\build\\update_modules\\Graphviz\\bin"
build: off

test_script:
  - "%PYTHON%\\python -u setup.py unittests"

after_test:
  - "%PYTHON%\\python -u setup.py bdist_wheel"

artifacts:
  - path: dist
    name: jupytalk
